global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'farutech-orchestrator'
    static_configs:
      - targets: ['host.docker.internal:5000']
    scrape_interval: 5s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

  - job_name: 'farutech-nats'
    static_configs:
      - targets: ['nats:8222']
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'farutech-postgres'
    static_configs:
      - targets: ['postgres:9187']
    scrape_interval: 10s